services:
#  app:
#    build: .
#    container_name: lemon_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy

  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    container_name: lemon_psql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lemonpass
      POSTGRES_DB: lemon
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./pkg/infra/psql/migrations/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db:
    driver: local
